### ISSUE TITLE
node js  gemfire on windows give errors while install

### ISSUE THREAD

**Issue by luckyprit** [gemfire/node-gemfire#8]
I get following error .  please advice .  log file is attached .

[npm-debug.log.txt](https://github.com/gemfire/node-gemfire/files/1252084/npm-debug.log.txt)

npm install --save  gemfire

> gemfire@0.1.19 install C:\Nodejs\express\node_modules\gemfire
> node-pre-gyp install --fallback-to-build

(node:25088) fs: re-evaluating native module sources is not supported. If you ar
e using the graceful-fs module, please update it to a more recent version.
(node:25088) DeprecationWarning: child_process: options.customFds option is depr
ecated. Use options.stdio instead.
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Nodejs\node_modules\npm\node_modules\node-gyp\lib\confi
gure.js:404:11
gyp ERR! stack     at C:\Nodejs\node_modules\npm\node_modules\graceful-fs\polyfi
lls.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Nodejs\\node.exe" "C:\\Nodejs\\node_modules\\npm\\node_mod
ules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--name=gemfire" "--configuration=Re
lease" "--module_name=gemfire" "--version=0.1.19" "--minor=1" "--patch=19" "--ru
ntime=node" "--node_abi=node-v48" "--platform=win32" "--target_platform=win32" "
--arch=x64" "--target_arch=x64" "--module_main=./lib" "--host=https://download.p
ivotal.com.s3.amazonaws.com/" "--module_path=C:\\Nodejs\\express\\node_modules\\
gemfire\\lib\\binding\\Release\\node-v48-win32-x64" "--module=C:\\Nodejs\\expres
s\\node_modules\\gemfire\\lib\\binding\\Release\\node-v48-win32-x64\\gemfire.nod
e" "--remote_path=./node-gemfire/0.1.19/" "--package_name=gemfire-v0.1.19-node-v
48-win32-x64.tar.gz" "--staged_tarball=build\\stage\\node-gemfire\\0.1.19\\gemfi
re-v0.1.19-node-v48-win32-x64.tar.gz" "--hosted_path=https://download.pivotal.co
m.s3.amazonaws.com/node-gemfire/0.1.19/" "--hosted_tarball=https://download.pivo
tal.com.s3.amazonaws.com/node-gemfire/0.1.19/gemfire-v0.1.19-node-v48-win32-x64.
tar.gz"
gyp ERR! cwd C:\Nodejs\express\node_modules\gemfire
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Nodejs\node.exe C:\Nodejs\n
ode_modules\npm\node_modules\node-gyp\bin\node-gyp.js rebuild --name=gemfire --c
onfiguration=Release --module_name=gemfire --version=0.1.19 --minor=1 --patch=19
 --runtime=node --node_abi=node-v48 --platform=win32 --target_platform=win32 --a
rch=x64 --target_arch=x64 --module_main=./lib --host=https://download.pivotal.co
m.s3.amazonaws.com/ --module_path=C:\Nodejs\express\node_modules\gemfire\lib\bin
ding\Release\node-v48-win32-x64 --module=C:\Nodejs\express\node_modules\gemfire\
lib\binding\Release\node-v48-win32-x64\gemfire.node --remote_path=./node-gemfire
/0.1.19/ --package_name=gemfire-v0.1.19-node-v48-win32-x64.tar.gz --staged_tarba
ll=build\stage\node-gemfire\0.1.19\gemfire-v0.1.19-node-v48-win32-x64.tar.gz --h
osted_path=https://download.pivotal.com.s3.amazonaws.com/node-gemfire/0.1.19/ --
hosted_tarball=https://download.pivotal.com.s3.amazonaws.com/node-gemfire/0.1.19
/gemfire-v0.1.19-node-v48-win32-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Nodejs\express\node_
modules\gemfire\node_modules\node-pre-gyp\lib\util\compile.js:76:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:891:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Nodejs\\node.exe" "C:\\Nodejs\\express\\node_modu
les\\gemfire\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallba
ck-to-build"
node-pre-gyp ERR! cwd C:\Nodejs\express\node_modules\gemfire
node-pre-gyp ERR! node -v v6.11.2
node-pre-gyp ERR! node-pre-gyp -v v0.5.31
node-pre-gyp ERR! not ok
Failed to execute 'C:\Nodejs\node.exe C:\Nodejs\node_modules\npm\node_modules\no
de-gyp\bin\node-gyp.js rebuild --name=gemfire --configuration=Release --module_n
ame=gemfire --version=0.1.19 --minor=1 --patch=19 --runtime=node --node_abi=node
-v48 --platform=win32 --target_platform=win32 --arch=x64 --target_arch=x64 --mod
ule_main=./lib --host=https://download.pivotal.com.s3.amazonaws.com/ --module_pa
th=C:\Nodejs\express\node_modules\gemfire\lib\binding\Release\node-v48-win32-x64
 --module=C:\Nodejs\express\node_modules\gemfire\lib\binding\Release\node-v48-wi
n32-x64\gemfire.node --remote_path=./node-gemfire/0.1.19/ --package_name=gemfire
-v0.1.19-node-v48-win32-x64.tar.gz --staged_tarball=build\stage\node-gemfire\0.1
.19\gemfire-v0.1.19-node-v48-win32-x64.tar.gz --hosted_path=https://download.piv
otal.com.s3.amazonaws.com/node-gemfire/0.1.19/ --hosted_tarball=https://download
.pivotal.com.s3.amazonaws.com/node-gemfire/0.1.19/gemfire-v0.1.19-node-v48-win32
-x64.tar.gz' (1)
npm WARN couchbase_trial@1.0.0 No repository field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Nodejs\\node.exe" "C:\\Nodejs\\node_modules\\npm\\bin\\npm-cl
i.js" "install" "gemfire"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! gemfire@0.1.19 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gemfire@0.1.19 install script 'node-pre-gyp install --fal
lback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gemfire package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gemfire
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gemfire
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Nodejs\express\npm-debug.log

**Comment by aaa-paul** [comment]
@luckyprit did you happen to fix this problem?
